# Dockerfile.client

# Use the official Nginx image as the base
FROM nginx:alpine

# Copy the published Blazor WebAssembly client files to Nginx's HTML folder
COPY . /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
